### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by waynehaffenden** [jaedle/cleanup-docker#1]
Since updating to the latest release the container never starts and fails with: standard_init_linux.go:228: exec user process caused: exec format error? This used to work great!

**Comment by jaedle** [comment]
Hey 👋 

I recently changed something on my ci-cd-chain. I will have a look.

**Comment by jaedle** [comment]
Should be fixed right now  😄

**Comment by waynehaffenden** [comment]
Wow that was fast and yes all fixed, thank you!

**Comment by jaedle** [comment]
You're welcome and sorry for the trouble! 🙏
